name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.X
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
         # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: 2.2.172
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
